# Generated by Django 3.2.13 on 2022-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_logins_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_logins_started',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
